name: 'ZyAction: Verify Changed Files'

description: Verify file changes that occur during workflow execution.
author: Florian Bernd

branding:
  icon: check-square
  color: green

inputs:
  exclude-ignored:
    description: >
      Whether to exclude `.gitignore` ignored files from the changed files detection.

      Defaults to `true`.
    type: boolean
    required: false
    default: true
  return-pipe:
    description: >
      Enable this option to return a shell (bash) command in the `pipe` output that can be
      used for piping.

      The output command must be `eval`ed to return the results. It can also be passed to 
      other actions that support a `pipe` input.

      The `changed-files` output will not be populated if this option is enabled.
    type: boolean
    required: false
    default: false

outputs:
  changed-files:
    description: >
      The list of all changed files, or an empty string.

      This output is only available if the `return-pipe` option is not enabled.
    value: ${{ steps.verify.outputs.changed-files }}
  pipe:
    description: >
      A shell (bash) command which can be used for piping.
      
      This output is only available if the `return-pipe` option is enabled.
    value: ${{ steps.verify.outputs.pipe }}

runs:
  using: composite
  steps:
    - name: Verify Changed Files
      id: verify
      shell: bash
      env:
        INPUT_EXCLUDE_IGNORED: ${{ inputs.exclude-ignored != 'false' && 'true' || 'false' }}
        INPUT_RETURN_PIPE: ${{ inputs.return-pipe != 'false' && 'true' || 'false' }}
      run: |
        "${{ github.action_path }}/entrypoint.sh"
