name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: 'TEST: Expect No Changes'
        id: test-no-changes
        uses: ./.github/actions/wrapper
        with:
          path: |
            test/*.txt
            test/*.sql
            test/**/*.txt
            test/**/*.sql
      - name: FAILED
        if: steps.test-no-changes.outputs.changed-files != ''
        run: |
          echo "Changed Files:"
          echo "${{ steps.test-no-changes.outputs.changed-files }}"
          exit 1

      - name: Modify File
        run: |
          printf '%s\n' "123" "456" >> test/new.txt

      - name: 'TEST: Expect Changes (modified)'
        id: test-modified
        uses: ./.github/actions/wrapper
        with:
          path: |
            test/*.txt
            test/*.sql
            test/**/*.txt
            test/**/*.sql
      - name: FAILED
        if: steps.test-modified.outputs.changed-files != '''test/new.txt'''
        run: |
          echo "Changed Files:"
          echo "${{ steps.test-modified.outputs.changed-files }}"
          exit 1

      - name: Create File
        run: |
          echo "test" > unstaged.txt

      - name: 'TEST: Expect Changes (added)'
        id: test-added
        uses: ./.github/actions/wrapper
        with:
          path: |
            unstaged.txt
      - name: FAILED
        if: steps.test-added.outputs.changed-files != '''unstaged.txt'''
        run: |
          echo "Changed Files:"
          echo "${{ steps.test-added.outputs.changed-files }}"
          exit 1

      - name: Delete File
        run: |
          rm test/new.sql

      - name: 'TEST: Expect Changes (deleted)'
        id: test-deleted
        uses: ./.github/actions/wrapper
        with:
          path: |
            test/new.sql
      - name: FAILED
        if: steps.test-deleted.outputs.changed-files != '''test/new.sql'''
        run: |
          echo "Changed Files:"
          echo "${{ steps.test-unstaged.deleted.changed-files }}"
          exit 1

      - name: 'TEST: Expect Changes (unstaged)'
        id: test-unstaged
        uses: ./.github/actions/wrapper
        with:
          path: |
            unstaged.txt
      - name: FAILED
        if: steps.test-unstaged.outputs.changed-files != '''unstaged.txt'''
        run: |
          echo "Changed Files:"
          echo "${{ steps.test-unstaged.outputs.changed-files }}"
          exit 1

      - name: 'TEST: Expect Changes (all)'
        id: test-all
        uses: ./.github/actions/wrapper
        with:
          path: |
            test/new.txt
            unstaged.txt
            test/new.sql
      - name: FAILED
        if: steps.test-all.outputs.changed-files != '''test/new.sql'' ''test/new.txt'' ''unstaged.txt'''
        run: |
          echo "Changed Files:"
          echo "${{ steps.test-all.outputs.changed-files }}"
          exit 1
